### ISSUE TITLE
[Info] PC-98 CD adds a blank "Copy protection" line to submissioninfo.txt

### ISSUE THREAD

**Issue by FoxhackDN** [SabreTools/MPF#374]
**Is your information related to one of the dumping programs supported or something that isn't a bug in the code? Please describe.**
When dumping a PC-98 disc, the submissioninfo.txt file contains an unneeded Copy Protection section. Neither MPF nor DIC scan for any protection on the disc. (The protection is usually in the floppies, anyway.)

Currently using build 2.3-621011af.

**Additional context**
![image](https://user-images.githubusercontent.com/71686027/158049941-e501c4b8-e20c-4896-980f-e823ae3593cc.png)

**Comment by mnadareski** [comment]
Possibly addressed by https://github.com/SabreTools/MPF/commit/0bf85ec729865362680eaaa8ce853ac33896a66d

**Comment by mnadareski** [comment]
I can't reproduce or fix this for the life of me. I probably need help.

**Comment by mnadareski** [comment]
Possibly addressed by https://github.com/SabreTools/MPF/commit/9a5feee095a703adf046cb5a1121a8f5f759d36e

**Comment by FoxhackDN** [comment]
Still happens. :( Disc dumped as PC-98, get a blank line. I got the latest build to make sure (artifact 841.)

**Comment by mnadareski** [comment]
Possibly addressed by https://github.com/SabreTools/MPF/commit/80156e73d193463314dabda80fd6b9cd76a2e747

**Comment by mnadareski** [comment]
Finally confirmed as fixed.
