### ISSUE TITLE
[Problem] Version isn't being filled for PS3 discs

### ISSUE THREAD

**Issue by Ragowit** [SabreTools/MPF#705]
**Version**
- [x] WIP release 3.1.9-4e982aa8679689c23a2ee7c43b7b7361f4101a7d

**Build**
- [x] .NET 8.0 running on Win 11 23H2

**Describe the issue**
After a PS3 dump so is the Version field filled with "(REQUIRED, IF EXISTS)" instead of the actual version.

**To Reproduce**
Dump a PS3 disc, look at the Version field.

**Expected behavior**
To have the version field filled with the actual version.

**Screenshots**
![image](https://github.com/SabreTools/MPF/assets/31790/c7f62499-dbf1-4b10-a521-657cae88fa29)

**Comment by mnadareski** [comment]
Should be fixed as of https://github.com/SabreTools/MPF/commit/4bb02b88fc830e3850dbf72d4b0515ebde09514d

**Comment by Ragowit** [comment]
Still an issue with 3.1.9a

![image](https://github.com/SabreTools/MPF/assets/31790/2985a56a-30cb-43f9-9708-c53dba62337d)

**Comment by mnadareski** [comment]
Should be fixed as of https://github.com/SabreTools/MPF/commit/70114ee59e42811664dce687b81da967d88fbf62

**Comment by Ragowit** [comment]
Works now, thanks!
