### ISSUE TITLE
[Request] Support re-parsing when no longer have .bin/.cue/.iso

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#905]
**Is your feature request related to a problem? Please describe.**
My workflow, when doing verifications for redump, is to dump the disc with redumper and then immediately delete the large .iso or .bin files to save disc space. I later run MPF.Check, pointing it at the .log file (the usage says to do `MPF.Check <system> [options] </path/to/output.cue/iso> ...` but the .log file works too).

Sometimes I have to do multiple passes of MPF.Check to refine things (e.g. add ringcodes using a seed file and so on). The new feature introduced in #896 is great for this, as it will unzip previous logs, if they were zipped previously.

However, because I no longer have a .bin/.iso file, and the .log is zipped up, I have nothing to point MPF.Check to. (It's possible it would work if I kept the small .cue file, but given than I'm mostly dumping DVDs and BDs, I don't have those).

**Describe the solution you'd like**
It would be great if MPF.Check would take a folder name as a parameter (assuming the folder only has one dumped disc in it), or take the .zip file as a parameter. At the moment, neither seem to work for me.

**Describe alternatives you've considered**
Obviously I could avoid zipping up the logs until I know that I'm done, and that is indeed what I currently do. I'm just thinking that it would be nice to take advantage of the work in #896 when I no longer have a .bin/.cue/.iso, given that, generally speaking, MPF.Check doesn't actually need those to do its thing. Thanks!

**Comment by mnadareski** [comment]
Out of all of those, the cuesheet is the hardest to avoid needing for CDs. That being said, whatever file you point at will be used as the "base path" for anything that's being checked. Normally it's the BIN/CUE/ISO, but if the logs were named identically to the image and you point at that, it will also work. It's hard to get that across in the help text.

**Comment by mnadareski** [comment]
To fix the possibility of a missing cuesheet in the main folder, I've added the ability to zip the cuesheets while still keeping them in the output directory. This means that situations where only the log zip is available should fully work with no extra effort. This was introduced in https://github.com/SabreTools/MPF/commit/584b8c01090e3e3f90effac5e2ffa078038925d6 which will be merged into the main branch along with everything else there later.

**Comment by JohnVeness** [comment]
Thanks for all your work on this :)

**Comment by mnadareski** [comment]
Fixed as of https://github.com/SabreTools/MPF/commit/c6258b5520c6b72e60e57024e4745ffc58d1bca1 and https://github.com/SabreTools/MPF/commit/584b8c01090e3e3f90effac5e2ffa078038925d6

**Comment by JohnVeness** [comment]
I'm trying 3.5.0-6eb976c8421b43fe80c03a30059a26b909daa51d which should have these changes. I'm not sure if I'm doing something wrong but it's still not working for me, when I only have zipped logs available for a dumped BD.

If I do `MPF.Check -u redumper gamefolder/gamename_logs.zip` I get:

```
Gathering submission information... please wait!
Extracting output information from output files...
There was an issue extracting information!
There were files missing from the output:
gamename_logs.log
gamename_logs.dat
gamename_logs.physical
gamename_logs.state
This may indicate an issue with the hardware or media, including unsupported devices.
Please see dumping program documentation for more details.
```

If I try and fake things as mentioned in your comment https://github.com/SabreTools/MPF/issues/905#issuecomment-3419066168 that doesn't work either, e.g. `MPF.Check -u redumper gamefolder/gamename.log` or `MPF.Check -u redumper gamefolder/gamename.iso` when neither are in the folder (in the case of the .log file, it is zipped up), I get:

```
gamefolder/gamename.iso does not exist
Usage:
MPF.Check <system> [options] </path/to/output.cue/iso> ...
etc.
```

Have I misunderstood?

**Comment by mnadareski** [comment]
The requirement of a real file existing was an old check that I had in there due to some limitations. I removed that part in https://github.com/SabreTools/MPF/commit/ac6a77d9da88aa8174fd5aeb087a5f3ce52b3d15

**Comment by mnadareski** [comment]
Ah ha, I found it. There's another place where the original full input path is used. I just need to handle that in the same way with the zip removal.

**Comment by mnadareski** [comment]
The secondary place has been fixed in https://github.com/SabreTools/MPF/commit/ff0c742deeedf1158d3b06366a499e8a8ef1043e

**Comment by mnadareski** [comment]
It only unzips if all files are found. I guess I have the state file as a required piece, even though it's not used for anything. That's just an oversight that can be fixed.

As for the first thing you're seeing, that's actually intended behavior. The log being extracted makes finding the internal media type easier.

**Comment by mnadareski** [comment]
Given that the state file is not strictly needed for output parsing, I've removed the optional-required flag on it as of https://github.com/SabreTools/MPF/commit/071e3a0024a09d203281a7e2d0877e1b7a4a60f5

**Comment by Deterous** [comment]
If you're passing a zip, can you check that the new zip still has the same set of files as the old one? As a sanity check.

**Comment by JohnVeness** [comment]
> If you're passing a zip, can you check that the new zip still has the same set of files as the old one? As a sanity check.

I'm not sure if that's a comment for me or for @mnadareski, but certainly for my test dump, for which I now have four zips, each zip has the same .log, .physical, .state.zst files with same checksum. The !submissionInfo.txt varies of course, due to the version number of MPF for example.
